name: Build

on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Compile sketch for ESP8266
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp8266:esp8266:d1_mini
          platforms: |
            - name: esp8266:esp8266
              version: 3.1.2
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - steampunk-clock.ino
          libraries: |
            - name: Adafruit BusIO
              version: 1.17.4
            - name: Adafruit PCF8574
              version: 1.1.2
            - name: OneButton
              version: 2.6.1
            - name: RTClib
              version: 2.1.4
            - name: WiFiManager
              version: 2.0.17
          enable-warnings-report: true

      - name: Compile sketch for ESP32
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:ESP32
          platforms: |
            - name: esp32:esp32
              version: 3.3.7
              source-url: https://arduino.esp32.com/stable/package_esp32com_index.json
          sketch-paths: |
            - steampunk-clock.ino
          libraries: |
            - name: Adafruit BusIO
              version: 1.17.4
            - name: Adafruit PCF8574
              version: 1.1.2
            - name: OneButton
              version: 2.6.1
            - name: RTClib
              version: 2.1.4
            - name: WiFiManager
              version: 2.0.17
            - name: ESP32Servo
              version: 3.1.3
          enable-warnings-report: true

      - name: Lint sketch
        uses: arduino/arduino-lint-action@v2
        with:
          project-type: sketch
          verbose: true
          compliance: strict
